typedef struct{
    char name[20];
    char wonsan[20];
    char info[200];
    char weight[20];
    int price;
    int ship;
} Product;
int loadData(Product*p);
int addProduct(Product *p);
int selectMenu();
void readProduct(Product p);
void listProduct(Product *p, int count);
int updateProduct(Product *p);
int deleteProduct(Product *p);
int selectDataNo(Product *p, int count);
void findByName(Product*p, int index);
void findByInfo(Product*p, int index);
void findByWonsanji(Product*p, int index);
void saveProduct(Product*p, int count);
